name: D4L SDK CI (Release)

on:
  push:
    branches:
      - release/**

jobs:
  release-check:
    runs-on: macos-latest

    env:
      D4L_EXAMPLE_CONFIG: ${{ secrets.D4L_EXAMPLE_CONFIG }}
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Display runner context
      run: hostname -s
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
    - name: Test podspec
      run: bundle exec fastlane test_podspec
