name: D4L SDK CI (PR Testing)

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - release/**

jobs:
  release-check:
    runs-on: macos-latest

    env:
      D4L_EXAMPLE_CONFIG: ${{ secrets.D4L_EXAMPLE_CONFIG }}

    steps:
    - name: Display runner context
      run: hostname -s
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Cache Swift packages
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-
    - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
    - name: Reset iOS simulators (Required to avoid tests failing problem)
      run: xcrun simctl erase all
    - name: Generate iOS Config JSON
      run: printf '%s\n' "$D4L_EXAMPLE_CONFIG" > d4l-example-app-config.json
    - name: Lint code
      run: bundle exec fastlane lint
    - name: Test code
      run: bundle exec fastlane test
    - name: Test podspec
      run: bundle exec fastlane test_podspec
